// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMaB8mNjarl3CcjXW21N7ci4qQVLal88',
    appId: '1:667352640129:web:6e1208f54036333848fb80',
    messagingSenderId: '667352640129',
    projectId: 'blog-app-101909',
    authDomain: 'blog-app-101909.firebaseapp.com',
    storageBucket: 'blog-app-101909.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIeepHRKXPO3k_r9MZB90XedG-7sBj1IU',
    appId: '1:667352640129:android:0a84ce9e00bd578848fb80',
    messagingSenderId: '667352640129',
    projectId: 'blog-app-101909',
    storageBucket: 'blog-app-101909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJS1aPUXRYWoOOndcmri4hncG-Uq4By74',
    appId: '1:667352640129:ios:ef40b91194a1da0c48fb80',
    messagingSenderId: '667352640129',
    projectId: 'blog-app-101909',
    storageBucket: 'blog-app-101909.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

}